### PR TITLE
RFC: build Kubernetes from vendor in workspace mode

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind feature

#### What this PR does / why we need it:

Go does not support using the source in "vendor" in workspace mode.
But in Kubernetes we want to commit the source code of our dependencies in the
repo to:

    - review that source code
    - support offline builds
    - have a 100% guarantee that the source code for dependencies
      doesn't get lost (the Google proxy cache doesn't guarantee that).
    
To get around this, the new generate-go-cache.sh converts the "vendor" source
code so that Go will find and use it in the module download cache. This is a
hack because it relies on the current implementation of zip file checking in
Go, which might change.
    
The .mod file of dependencies are needed. They normally don't get vendored, so
update-vendor.sh must take care of that itself.
    
TODO: update-vendor.sh is currently broken because of the gengo hack. Once
there is a genkgo/v2 in the upstream repo, update-vendor.sh needs to be
updated (move the new code, remove obsolete functionality).

### CODE REVIEW

**Comment by thockin** [comment]
It feels like it should be simpler to just `go mod download` to a local dir and then check that in?  It's approximately the same as vendoring and I guess we can verify it the same way - run it again and look for diffs.

It feels dirty, but it's simple?

**Comment by pohly** [comment]
`go mod download` has several issues:

- Source code is unpacked into directories with names that contain the version (for example, `go.opentelemetry.io/otel@v0.20.0`). A GitHub diff then might not show the actual file diff during an update, which will make reviewing a vendor update harder.
- If I remember correctly, you said that a single invocation didn't download all packages. I haven't tried to verify that.
- The entire source code is unpacked, including .go files that we don't need for building Kubernetes and `_test.go` files. If we don't fix that via some post-processing, then vendor reviews will become harder. If we add such post-processing, then it's not simple anymore.
- Building from this pre-populated GOMODCACHE directory only works if the `cache/download` directory with the .zip files is present. Even then it had problems that would need further investigations.

I consider the first point a show stopper and I don't see a good way around it. Perhaps we can play trick with symlinks.

The last point is a problem if we intend to make Kubernetes buildable without relying on source code downloads. Is that required or is it just a stretch goal?

**Comment by pohly** [comment]
I've rebased, but it's not fully working ATM.

My previous approach for ensuring a populated mod cache was hooking into the Makefile dependencies for generated files, but that went away. I probably need to go exclusively for shell code.

**Comment by thockin** [comment]
Vendor works in go next or next-next!

**Pull request closed without merging**
