### PR TITLE
go workspaces: simplify go.work file

### PR DESCRIPTION
**Pull request by pohly**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:

It doesn't seem necessary to have replace statements in the go.work file as long as the individual go.mod files are consistent, which should be the goal.

#### Special notes for your reviewer:

[code-generator/examples: sync sigs.k8s.io/json replacement](https://github.com/thockin/kubernetes/commit/2bd44601354e321d54d66a24357e5468c8fb05f6) belongs before the [prefactoring before this](https://github.com/kubernetes/kubernetes/pull/110374/commits/4eb21fde38b20a8c9071afd480b99c0959ed1de7). The script can be added as first commit, followed by the generated file.

#### Does this PR introduce a user-facing change?
```release-note
NONE
```

### CODE REVIEW

**Comment by thockin** [comment]
What happens is 2 modules use different versions:

```
$ make kubectl
+++ [0608 09:53:57] Building go targets for linux/amd64
    ./hack/make-rules/helpers/go2make (non-static)
go: conflicting replacements for sigs.k8s.io/json:
	sigs.k8s.io/json@v0.0.0-20211208200746-9f7c6b3444d2
	github.com/liggitt/json@v0.0.0-20211020163728-48258682683b
use "go work edit -replace sigs.k8s.io/json=[override]" to resolve
!!! [0608 09:53:57] Call tree:
!!! [0608 09:53:57]  1: /home/thockin/src/go/src/k8s.io/kubernetes/hack/lib/golang.sh:733 kube::golang::build_some_binaries(...)
!!! [0608 09:53:57]  2: /home/thockin/src/go/src/k8s.io/kubernetes/hack/lib/golang.sh:893 kube::golang::build_binaries_for_platform(...)
!!! [0608 09:53:57]  3: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0608 09:53:57] Call tree:
!!! [0608 09:53:57]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
!!! [0608 09:53:57] Call tree:
!!! [0608 09:53:57]  1: hack/make-rules/build.sh:27 kube::golang::build_binaries(...)
make[1]: *** [Makefile.generated_files:78: .make/go-pkgdeps.mk] Error 1
make: *** [Makefile:536: generated_files] Error 2
```

After patching your first commit, it builds.

You've touched something I don't have an answer on yet - which model is better and why?  On one hand, it seems nice that go.work is the canonical source of truth for all dep-versions.  But then we have to generate the "real" go.mod for staging repos when we publish them, which means those published repos hold commits that are NOT in k/k (which I think we do not want?).

On the other hand, keeping all the individual go.mod files in sync requires some baroque logic and scripts. But we already have those.  But... how did the first commit in this PR happen in the first place?  Did the existing scripts miss something?  Is that the only one?  How do we know?

Unsurprisingly, @liggitt holds more context on this than probably anyone else.  Jordan, for context: We're edging closer to a working PR for Go Workspaces, collaborating in my branch for now.   To make early progress I just assumed it was easier to import enverything into go.work, but I am less convinced that this works "for real".  Your input is welcome :)

This is not (yet) touching the question of vendor vs GOPROXY vs ...

**Comment by thockin** [comment]
Something this PR doesn't do - propagate the gengo/v2 and kube-openapi hacks I made into other go.mod files.  How can I tell what is happening when I remove those from go.work?  Where is staging/src/k8s.io/code-generator/cmd/deepcopy-gen/ getting "k8s.io/gengo/v2/*" from?

**Comment by pohly** [comment]
> What happens is 2 modules use different versions

I think we don't want that to happen. That it occurred for `staging/src/k8s.io/code-generator/examples/go.mod` seems like a historic artifact.

> On the other hand, keeping all the individual go.mod files in sync requires some baroque logic and scripts. But we already have those.

Right, and `hack/update-vendor.sh` should continue to work when it sets `GOWORK=off`. It's currently broken because of the gengo/v2 hack (doesn't find that version), but that should be temporary. If a developer makes changes in go.work, they first need to sync back into go.mod with `go work sync` and then run that script. The script could also do `go work sync`, just to be sure.

> This is not (yet) touching the question of vendor vs GOPROXY vs ...

I am working on a solution that uses the vendor dir to populate GOMODCACHE/download. Then builds should work with `GOPROXY=off` (i.e. don't download anything). Might work and/or might be a horrible hack... :sweat_smile: 

> Something this PR doesn't do - propagate the gengo/v2 and kube-openapi hacks I made into other go.mod files. How can I tell what is happening when I remove those from go.work?

I think in workspace mode it will use the sources from "./gengo2" because of the "use" statement. Before publishing those staging repos, the k8s.io/gengo/v2 release must be published properly.

**Comment by thockin** [comment]
How do we expect this script to be run?  Should we rely on it being manually run, or should it be part of `hack/update-all.sh`, or should it be run as part of something else?

I'm thinking it should probably be `hack/update-go-workspace.sh` and `hack/verify-go-workspace.sh` ?

**Comment by thockin** [comment]
Integrated.  I changed it to update/verify and integrated that with your commit.

Force-pushed.

**Comment by pohly** [comment]
> I'm not super concerned about GOWORK=off - supporting that means we have to keep most of the old crufty logic to cross modules. I think (once we get it working) workspaces are it.

It would only be used for running "go mod vendor". Everything else will run in workspace mode. My biggest concern was the complicated logic in `update-vendor.sh`, but after thinking about it some more, I see room for simplifications in it exactly because we no longer have to support non-workspace builds anymore.

**Comment by liggitt** [comment]
> go: conflicting replacements for sigs.k8s.io/json:
> 	sigs.k8s.io/json@v0.0.0-20211208200746-9f7c6b3444d2
> 	github.com/liggitt/json@v0.0.0-20211020163728-48258682683b

oof... that replace should never have merged... I'll fix that up now

**Comment by liggitt** [comment]
opened https://github.com/kubernetes/kubernetes/pull/110546 to drop the `replace` from the examples go.mod file entirely

**Comment by liggitt** [comment]
> how did the first commit in this PR happen in the first place? Did the existing scripts miss something? Is that the only one?

The vendor sync/verify scripts only pay attention to staging/src/k8s.io/$module/go.mod files, and prevent spurious replace directives in those files. The examples go.mod file is a weird fish, is one level deeper, is not referenced by any commands in the main module, does not impact vendor, and apparently is not touched or verified by our vendor sync scripts.

**Comment by pohly** [comment]
> The examples go.mod file is a weird fish, is one level deeper, is not referenced by any commands in the main module, does not impact vendor, and apparently is not touched or verified by our vendor sync scripts.

I suppose for workspace mode we should either ignore ignore such sub-modules or ensure that our vendor sync scripts cover them. I prefer the latter if it is not too much work, but won't spend too much time on it.

**Pull request merged**
